export const INITIAL_ENTITY_DATA = {
  shortDescription: "HETTETY is a premium real estate platform powered by AI, offering verified listings, 3D tours, and legal assistance."
};

export const TRANSLATIONS = {
  en: {
    prop_forsale: "For Sale",
    prop_forrent: "For Rent",
    prop_verified: "Verified",
    prop_view_3d: "View 3D",
    prop_beds: "Beds",
    prop_baths: "Baths",
    auth_welcome: "Welcome Back",
    auth_create: "Create Account",
    auth_login_desc: "Sign in to access your saved properties",
    auth_reg_desc: "Join us to find your dream home",
    auth_name: "Full Name",
    auth_email: "Email Address",
    auth_pass: "Password",
    auth_confirm: "Confirm Password",
    auth_signin_btn: "Sign In",
    auth_signup_btn: "Sign Up",
    auth_no_account: "Don't have an account?",
    auth_has_account: "Already have an account?",
    auth_or_continue: "Or continue with",
    auth_google: "Google",
    auth_apple: "Apple",
    auth_pass_req: "Min 8 chars & 1 special char.",
    auth_pass_weak: "Weak",
    auth_pass_fair: "Fair",
    auth_pass_good: "Good",
    auth_pass_strong: "Strong",
    nav_register: "Register",
    nav_login_short: "Login",
    tour_3d_badge: "Immersive Experience",
    tour_3d_title: "Explore Before You Visit",
    tour_3d_desc: "Step inside properties from anywhere in the world with our high-fidelity 3D tours.",
    tour_3d_loading: "Coming Soon...",
    tour_3d_tooltip: "Click to Enter 3D Mode",
    tour_3d_feat_1: "Virtual Reality",
    tour_3d_feat_1_desc: "Compatible with VR headsets",
    tour_3d_feat_2: "Measurements",
    tour_3d_feat_2_desc: "Measure any wall or furniture",
    tour_3d_feat_3: "Floor Plans",
    tour_3d_feat_3_desc: "View 2D schematic layouts",
    hero_verified_badge: "AI Verified Listings",
    hero_title: "Find Your Perfect",
    hero_span: "Sanctuary",
    hero_desc: "Discover verified premium properties with the power of AI assistance and immersive 3D tours.",
    hero_cta: "Browse Properties",
    feat_title: "Why Choose HETTETY",
    feat_desc: "We combine cutting-edge technology with real estate expertise.",
    feat_1_title: "Verified Listings",
    feat_1_desc: "Every property is physically verified by our team.",
    feat_2_title: "Legal Assistance",
    feat_2_desc: "AI-powered contract analysis and generation.",
    feat_3_title: "3D Tours",
    feat_3_desc: "Walk through properties without leaving home.",
    feat_4_title: "AI Support",
    feat_4_desc: "24/7 assistance for all your questions.",
    ai_welcome: "Hello! I'm your HETTETY AI assistant. How can I help you find your dream property today?",
    ai_title: "HETTETY AI",
    ai_subtitle: "Real Estate Assistant",
    ai_thinking: "Thinking...",
    ai_placeholder: "Ask about prices, locations, or legal advice...",
    ai_quick_1: "Show me apartments in Cairo",
    ai_quick_2: "What are the legal fees?",
    ai_quick_3: "Investment opportunities",
    legal_title: "Legal Center",
    legal_subtitle: "Manage your documents and contracts securely.",
    legal_analyzing: "Analyzing...",
    legal_upload: "Upload Document",
    legal_status: "Status Overview",
    legal_stat_1: "Documents Verified",
    legal_stat_2: "Pending Review",
    legal_stat_3: "Action Required",
    nav_home: "Home",
    nav_listings: "Listings",
    nav_3d_exp: "3D Experience",
    nav_trust: "Trust & Legal",
    nav_ai: "AI Assistant",
    nav_login: "Login",
    prop_featured: "Featured Properties",
    prop_subtitle: "Hand-picked for you",
    prop_view_all: "View All",
    prop_avail: "Available Properties",
    prop_search: "Search by location, price, or type...",
    contact_title: "Contact Us",
    contact_desc: "We're here to help you.",
    contact_msg: "Message",
    contact_btn: "Send Message",
    footer_desc: "Premium Real Estate Platform",
    footer_services: "Services",
    footer_buy: "Buy Property",
    footer_verify: "Verify Documents",
    footer_3d: "3D Tours",
    footer_company: "Company",
    footer_about: "About Us",
    footer_terms: "Terms of Service",
    footer_connect: "Connect",
    // Premium Hero
    hero_badge: "AI Real Estate",
    hero_title_start: "Here Begins",
    hero_title_end: "Your Real Estate Future",
    hero_subtitle: "Discover verified opportunities powered by AI. Invest with confidence, choose smarter.",
    hero_cta_primary: "Start Now",
    hero_cta_secondary: "Explore Listings",
    // About Page
    about_badge: "About Us",
    about_title_start: "Future of",
    about_title_end: "Smart Real Estate",
    about_desc: "HETTETY is a smart real estate platform aiming to redefine the search and investment experience through technology and AI.",
    about_vision_title: "Our Vision",
    about_vision_desc: "To become the most trusted and innovative real estate platform in the Middle East.",
    about_mission_title: "Our Mission",
    about_mission_desc: "Empowering individuals and investors to make smart decisions via accurate data.",
    about_why_title: "Why HETTETY?",
    about_why_subtitle: "Combining innovation and reliability.",
    about_feat_1: "Advanced AI",
    about_feat_2: "Verified Listings",
    about_feat_3: "Interactive 3D Tours",
    about_feat_4: "Integrated Security",
    about_cta_title: "Join the future of smart real estate today",
    about_cta_btn: "Start Now",
    // Service Pages
    buy_title: "Smart Property Buying",
    buy_desc: "Discover your dream home among thousands of verified listings.",
    buy_cta: "Browse Properties",
    buy_feat_1_title: "Accurate Market Analysis",
    buy_feat_1_desc: "Real-time data on prices per meter.",
    buy_feat_2_title: "Exclusive Listings",
    buy_feat_2_desc: "Early access to best opportunities.",
    buy_feat_3_title: "Easy Financing",
    buy_feat_3_desc: "Smart loan calculator and bank partnerships.",
    verify_title: "Document Verification",
    verify_desc: "Comprehensive legal service to check property contracts.",
    verify_cta: "Start Verification",
    verify_feat_1_title: "Legal Check",
    verify_feat_1_desc: "Detailed review of ownership sequence.",
    verify_feat_2_title: "Violation Detection",
    verify_feat_2_desc: "Check for building violations.",
    verify_feat_3_title: "Certified Report",
    verify_feat_3_desc: "Receive a detailed legal report.",
    tours_title: "Virtual 3D Tours",
    tours_desc: "Walk inside the property as if you were there.",
    tours_cta: "Try Tour Now",
    tours_feat_1_title: "Stunning Realism",
    tours_feat_1_desc: "4K quality showing details.",
    tours_feat_2_title: "Measurements",
    tours_feat_2_desc: "Smart tool to measure rooms.",
    tours_feat_3_title: "Save Time",
    tours_feat_3_desc: "Save the hassle of field visits.",
    // Terms Page
    terms_badge: "Legal",
    terms_title: "Terms & Conditions",
    terms_desc: "Please read these terms carefully.",
    terms_sec_1_title: "Acceptance of Terms",
    terms_sec_1_desc: "By accessing HETTETY, you agree to these terms.",
    terms_sec_2_title: "Platform Use",
    terms_sec_2_desc: "Allowed for legal purposes only.",
    terms_sec_3_title: "Intellectual Property",
    terms_sec_3_desc: "All content is exclusive property of HETTETY.",
    terms_sec_4_title: "Liability",
    terms_sec_4_desc: "We strive for accuracy but do not guarantee it.",
    terms_sec_5_title: "Amendments",
    terms_sec_5_desc: "We reserve the right to modify terms.",
    terms_footer: "Last updated: Feb 23, 2026",
    // Consent & Legal
    consent_title: "Welcome to HETTETY",
    consent_desc: "Before you explore our premium real estate platform, please review and accept our policies. We use cookies to ensure you get the best experience.",
    consent_accept: "I Accept All Policies",
    consent_manage: "Manage Preferences",
    consent_save: "Save Preferences",
    consent_necessary: "Strictly Necessary Cookies",
    consent_necessary_desc: "Required for the website to function properly. Cannot be disabled.",
    consent_analytics: "Analytics Cookies",
    consent_analytics_desc: "Help us understand how visitors interact with the website.",
    consent_marketing: "Marketing Cookies",
    consent_marketing_desc: "Used to deliver personalized advertisements.",
    consent_terms_agree: "I have read and agree to the Terms & Conditions and Privacy Policy",
    nav_privacy: "Privacy Policy",
    nav_cookie: "Cookie Policy"
  },
  ar: {
    prop_forsale: "للبيع",
    prop_forrent: "للإيجار",
    prop_verified: "مؤكد",
    prop_view_3d: "عرض ثلاثي الأبعاد",
    prop_beds: "سرير",
    prop_baths: "حمام",
    auth_welcome: "مرحباً بعودتك",
    auth_create: "إنشاء حساب",
    auth_login_desc: "سجل الدخول للوصول إلى عقاراتك المحفوظة",
    auth_reg_desc: "انضم إلينا للعثور على منزل أحلامك",
    auth_name: "الاسم الكامل",
    auth_email: "البريد الإلكتروني",
    auth_pass: "كلمة المرور",
    auth_confirm: "تأكيد كلمة المرور",
    auth_signin_btn: "تسجيل الدخول",
    auth_signup_btn: "إنشاء حساب",
    auth_no_account: "ليس لديك حساب؟",
    auth_has_account: "لديك حساب بالفعل؟",
    auth_or_continue: "أو المتابعة باستخدام",
    auth_google: "جوجل",
    auth_apple: "آبل",
    auth_pass_req: "8 أحرف على الأقل ورمز خاص.",
    auth_pass_weak: "ضعيف",
    auth_pass_fair: "مقبول",
    auth_pass_good: "جيد",
    auth_pass_strong: "قوي",
    nav_register: "سجل الآن",
    nav_login_short: "دخول",
    tour_3d_badge: "تجربة غامرة",
    tour_3d_title: "استكشف قبل أن تزور",
    tour_3d_desc: "تجول داخل العقارات من أي مكان في العالم بجولات ثلاثية الأبعاد عالية الدقة.",
    tour_3d_loading: "قريباً...",
    tour_3d_tooltip: "انقر للدخول",
    tour_3d_feat_1: "واقع افتراضي",
    tour_3d_feat_1_desc: "متوافق مع نظارات VR",
    tour_3d_feat_2: "قياسات",
    tour_3d_feat_2_desc: "قس أي جدار أو أثاث",
    tour_3d_feat_3: "مخططات",
    tour_3d_feat_3_desc: "عرض مخططات ثنائية الأبعاد",
    hero_verified_badge: "عقارات موثقة بالذكاء الاصطناعي",
    hero_title: "اعثر على ملاذك",
    hero_span: "المثالي",
    hero_desc: "اكتشف عقارات فاخرة وموثقة بقوة المساعدة الذكية والجولات ثلاثية الأبعاد.",
    hero_cta: "تصفح العقارات",
    feat_title: "لماذا تختار حتتي",
    feat_desc: "نجمع بين التكنولوجيا المتطورة والخبرة العقارية.",
    feat_1_title: "عقارات موثقة",
    feat_1_desc: "يتم التحقق من كل عقار فعلياً بواسطة فريقنا.",
    feat_2_title: "مساعدة قانونية",
    feat_2_desc: "تحليل وإنشاء العقود بدعم الذكاء الاصطناعي.",
    feat_3_title: "جولات 3D",
    feat_3_desc: "تجول في العقارات دون مغادرة منزلك.",
    feat_4_title: "دعم ذكي",
    feat_4_desc: "مساعدة على مدار الساعة لجميع استفساراتك.",
    ai_welcome: "مرحباً! أنا مساعد حتتي الذكي. كيف يمكنني مساعدتك في العثور على عقار أحلامك اليوم؟",
    ai_title: "حتتي AI",
    ai_subtitle: "مساعد عقاري",
    ai_thinking: "يفكر...",
    ai_placeholder: "اسأل عن الأسعار، المواقع، أو نصائح قانونية...",
    ai_quick_1: "أرني شقق في القاهرة",
    ai_quick_2: "ما هي الرسوم القانونية؟",
    ai_quick_3: "فرص استثمارية",
    legal_title: "المركز القانوني",
    legal_subtitle: "أدر مستنداتك وعقودك بأمان.",
    legal_analyzing: "جاري التحليل...",
    legal_upload: "رفع مستند",
    legal_status: "نظرة عامة",
    legal_stat_1: "مستندات موثقة",
    legal_stat_2: "قيد المراجعة",
    legal_stat_3: "مطلوب إجراء",
    nav_home: "الرئيسية",
    nav_listings: "العقارات",
    nav_3d_exp: "تجربة 3D",
    nav_trust: "ثقة وقانون",
    nav_ai: "المساعد الذكي",
    nav_login: "دخول",
    prop_featured: "عقارات مميزة",
    prop_subtitle: "مختارة خصيصاً لك",
    prop_view_all: "عرض الكل",
    prop_avail: "العقارات المتاحة",
    prop_search: "ابحث بالموقع، السعر، أو النوع...",
    contact_title: "اتصل بنا",
    contact_desc: "نحن هنا لمساعدتك.",
    contact_msg: "الرسالة",
    contact_btn: "إرسال الرسالة",
    footer_desc: "منصة عقارية فاخرة",
    footer_services: "خدمات",
    footer_buy: "شراء عقار",
    footer_verify: "توثيق مستندات",
    footer_3d: "جولات 3D",
    footer_company: "الشركة",
    footer_about: "من نحن",
    footer_terms: "شروط الخدمة",
    footer_connect: "تواصل معنا",
    // Premium Hero
    hero_badge: "الذكاء الاصطناعي العقاري",
    hero_title_start: "هنا يبدأ",
    hero_title_end: "مستقبلك العقاري",
    hero_subtitle: "اكتشف فرصًا موثقة ومدعومة بالذكاء الاصطناعي. استثمر بثقة، واختر بقرار أذكى.",
    hero_cta_primary: "ابدأ الآن",
    hero_cta_secondary: "استكشف العقارات",
    // About Page
    about_badge: "من نحن",
    about_title_start: "مستقبل العقارات",
    about_title_end: "الذكية",
    about_desc: "HETTETY منصة عقارية ذكية تهدف إلى إعادة تعريف تجربة البحث والاستثمار العقاري من خلال التكنولوجيا والذكاء الاصطناعي.",
    about_vision_title: "رؤيتنا",
    about_vision_desc: "أن نصبح المنصة العقارية الأكثر ثقة وابتكارًا في الشرق الأوسط، من خلال تقديم حلول رقمية متطورة ترفع مستوى الشفافية والأمان.",
    about_mission_title: "مهمتنا",
    about_mission_desc: "تمكين الأفراد والمستثمرين من اتخاذ قرارات عقارية ذكية عبر بيانات دقيقة، توثيق موثوق، وتجربة تفاعلية ثلاثية الأبعاد.",
    about_why_title: "لماذا HETTETY؟",
    about_why_subtitle: "نجمع بين الابتكار والموثوقية لتقديم تجربة استثنائية",
    about_feat_1: "ذكاء اصطناعي متقدم",
    about_feat_2: "عقارات موثقة",
    about_feat_3: "جولات 3D تفاعلية",
    about_feat_4: "أمان رقمي متكامل",
    about_cta_title: "انضم إلى مستقبل العقارات الذكية اليوم",
    about_cta_btn: "ابدأ الآن",
    // Service Pages
    buy_title: "شراء عقار ذكي",
    buy_desc: "اكتشف منزل أحلامك من بين آلاف العقارات الموثقة. نستخدم الذكاء الاصطناعي لتحليل السوق وضمان أفضل سعر لك.",
    buy_cta: "تصفح العقارات",
    buy_feat_1_title: "تحليل سوق دقيق",
    buy_feat_1_desc: "بيانات فورية عن أسعار المتر وتوقعات النمو الاستثماري.",
    buy_feat_2_title: "عقارات حصرية",
    buy_feat_2_desc: "وصول مبكر لأفضل الفرص العقارية قبل طرحها في السوق العام.",
    buy_feat_3_title: "تمويل ميسر",
    buy_feat_3_desc: "حاسبة قروض ذكية وشراكات مع أكبر البنوك لتسهيل التمويل.",
    verify_title: "توثيق المستندات",
    verify_desc: "خدمة قانونية متكاملة لفحص وتوثيق عقود الملكية. احمِ استثمارك وتأكد من سلامة العقار قانونياً قبل الشراء.",
    verify_cta: "ابدأ التوثيق",
    verify_feat_1_title: "فحص قانوني شامل",
    verify_feat_1_desc: "مراجعة دقيقة لتسلسل الملكية والتراخيص من قبل خبراء.",
    verify_feat_2_title: "كشف المخالفات",
    verify_feat_2_desc: "التحقق من عدم وجود مخالفات بناء أو مستحقات مالية متأخرة.",
    verify_feat_3_title: "تقرير معتمد",
    verify_feat_3_desc: "استلم تقرير قانوني مفصل يضمن حقك ويحميك من الاحتيال.",
    tours_title: "جولات 3D افتراضية",
    tours_desc: "تجول داخل العقار وكأنك هناك. تقنية مسح ضوئي متطورة تتيح لك معاينة كل تفاصيل المنزل من مكانك.",
    tours_cta: "جرب الجولة الآن",
    tours_feat_1_title: "واقعية مذهلة",
    tours_feat_1_desc: "جودة 4K تظهر أدق التفاصيل والتشطيبات.",
    tours_feat_2_title: "قياس المساحات",
    tours_feat_2_desc: "أداة ذكية لقياس الغرف والأبعاد للتأكد من ملاءمة أثاثك.",
    tours_feat_3_title: "توفير الوقت",
    tours_feat_3_desc: "وفر عناء الزيارات الميدانية وعاين عشرات العقارات في دقائق.",
    // Terms Page
    terms_badge: "قانوني",
    terms_title: "الشروط والأحكام",
    terms_desc: "يرجى قراءة هذه الشروط بعناية قبل استخدام خدمات منصة HETTETY.",
    terms_sec_1_title: "قبول الشروط",
    terms_sec_1_desc: "بوصولك واستخدامك لمنصة HETTETY، فإنك توافق على الالتزام بهذه الشروط والأحكام.",
    terms_sec_2_title: "استخدام المنصة",
    terms_sec_2_desc: "يُسمح باستخدام المنصة للأغراض القانونية فقط.",
    terms_sec_3_title: "الملكية الفكرية",
    terms_sec_3_desc: "جميع المحتويات الموجودة على المنصة هي ملكية حصرية لـ HETTETY.",
    terms_sec_4_title: "المسؤولية",
    terms_sec_4_desc: "تسعى HETTETY لتقديم معلومات دقيقة، لكننا لا نضمن خلو المنصة من الأخطاء.",
    terms_sec_5_title: "التعديلات",
    terms_sec_5_desc: "نحتفظ بالحق في تعديل هذه الشروط في أي وقت.",
    terms_footer: "آخر تحديث: 23 فبراير 2026",
    // Consent & Legal
    consent_title: "مرحباً بك في HETTETY",
    consent_desc: "قبل استكشاف منصتنا العقارية الفاخرة، يرجى مراجعة وقبول سياساتنا. نحن نستخدم ملفات تعريف الارتباط لضمان حصولك على أفضل تجربة.",
    consent_accept: "أوافق على جميع السياسات",
    consent_manage: "إدارة التفضيلات",
    consent_save: "حفظ التفضيلات",
    consent_necessary: "ملفات تعريف الارتباط الضرورية",
    consent_necessary_desc: "مطلوبة لعمل الموقع بشكل صحيح. لا يمكن تعطيلها.",
    consent_analytics: "ملفات تعريف الارتباط التحليلية",
    consent_analytics_desc: "تساعدنا في فهم كيفية تفاعل الزوار مع الموقع.",
    consent_marketing: "ملفات تعريف الارتباط التسويقية",
    consent_marketing_desc: "تستخدم لتقديم إعلانات مخصصة.",
    consent_terms_agree: "لقد قرأت وأوافق على الشروط والأحكام وسياسة الخصوصية",
    nav_privacy: "سياسة الخصوصية",
    nav_cookie: "سياسة ملفات تعريف الارتباط"
  }
};
